### ISSUE TITLE
NWCollection.gait: device locations too specific

### ISSUE THREAD

**Issue by kitbeyer** [nimbal/nwpipeline#19]
The LA and RA device locations (lines 581+582) are specific to the way this data was coded. We probably can't account for all possible codings and we don't necessarily want to standardize so we should search for a limited set of possible codes.

I have created an attribute called device locations (line 129), can we take the device location, remove any spaces and underscores, make it upper case and search for it in the appropriate list in this dict?

**Comment by matthewwong525** [comment]
for removing spaces and underscores, would it be better to do this in the NWPipeline class? so we can have this change across all processes.;
