### ISSUE TITLE
NWCollection.gait: Warning messages

### ISSUE THREAD

**Issue by kitbeyer** [nimbal/nwpipeline#20]
Can the warnings be more specific?

I have added the subject and collection id to the start of the message as we should provide this info for people who filter the log to show only warnings.

I am confused about the difference between the two messages and why the first message aborts the function if one ankle is missing but the next few lines of code seem to account for if one ankle is missing. Perhaps I misunderstand.

**Comment by matthewwong525** [comment]
the gait code is weird, if I only want to process only one ankle, I need to input the same file/object twice for both feet. That being said, I will update the messages for clarity.
