### ISSUE TITLE
subjects.csv seed file to contain subject level info not included in raw data headers

### ISSUE THREAD

**Issue by kitbeyer** [nimbal/nwpipeline#47]

**Comment by kitbeyer** [comment]
Just study_code, subject_id, and dominant_hand variables for now.

Should be read in like devices.csv where appropriate either at start (NWPipeline) or just read the appropriate row for the subject in NWCollection.

Check for and return appropriate errors if subject is not in file, etc.

**Comment by matthewwong525** [comment]
If `subject.csv` does not exist then output warning? For now set dominant to right hand.
