### ISSUE TITLE
NWPipeline: status tracking mechanism

### ISSUE THREAD

**Issue by kitbeyer** [nimbal/nwpipeline#7]
Problem: the progress of data processing through the pipeline is not tracked and relies on visual inspection of output files to know whether or not specific processes have been performed on specific data

Create a method for tracking the status of processing of all data in the pipeline.

This could be an extension of the device list seed file or a dedicated file that mirrors the structure of the device list with a row for each device in the study. Columns could indicate status at the various stages through the pipeline as well as useful information such as filenames output at various stages (useful if we implement function to rename raw data files on conversion to edf).

An additional mechanism may need to be added to this to update the status based on users moving or deleting files within the pipeline.

**Comment by matthewwong525** [comment]
This will output a table, if it fails, "True, False, Or Empty(Didn'tTry)" for each stage. 

On initialize, create mirrored copy of device_list. with the status columns. First step is a table that someone can open and glance that tells you how the run is progressing after every stage. for something like gait? Have it per collection.
